### ISSUE TITLE
segmentation fault(core dumped)

### ISSUE THREAD

**Issue by yardenpage** [xinyadu/nqg#14]
hey everybody,
while trying to run the preprocessing part at the project,
at the comment: **th convert.lua**
there is an error : **segmentation fault(core dumped)**.
from the line:
"array = npy4th.loadnpy("qg.src.840B.300d.npy")"
the reading of the file is fail.
we didn't solve it yet, may one of you can help us,
thanks.

**Comment by TjebbeVQ** [comment]
Did you manage to fix it? I currently have problems readin the file, when i convert the code to use npz instead of npy i get segmentation fault too.

EDIT
Managed to fix it by using 6B 100d file instead of the 6B 50d file.
