### ISSUE TITLE
preprocessing part

### ISSUE THREAD

**Issue by talrose01** [xinyadu/nqg#15]
We want to know which path did you  replace at <path to embedding txt file> in preprocess_embedding.sh with real path?
thanks

**Comment by vedarddy** [comment]
Did you figure out which path works?

**Comment by Saren-Arterius** [comment]
For people who are lost, you are supposed to download a 2GB (unzipped 5GB) labels: https://nlp.stanford.edu/projects/glove/  Common Crawl (840B tokens, 2.2M vocab, cased, 300d vectors, 2.03 GB download): glove.840B.300d.zip

**Comment by adrien-jacquot** [comment]
Would be nice to add this part in the readme
