### ISSUE TITLE
About BLEU scores with default settings

### ISSUE THREAD

**Issue by ganymedetitan** [xinyadu/nqg#21]
Hi! Thank you for opensourcing your qg work.

I tried running with default parameters and because I got errors when running qgevalcap, I evaluated with bleus with coco-caption :
https://github.com/XgDuan/coco-caption/
And got 34.79/19.04/12.29/8.44 for BLEU1~4, which is a bit behind scores reported in ACL paper. 
I am not sure did I accidentally do something wrong since I am not familiar with lua codes, or is it just a different implementation/parameter with bleu scores (if there is)?

Sorry for very poor English. :/
Thank you very much!

**Comment by xinyadu** [comment]
my evaluation scripts are slightly different from the coco-caption scripts,
because they use images as keys, i used the input sentences as keys and
compare the output with *multiple* gold references of the input sentence, i
guess that's why you are getting lower scores.

**Comment by ganymedetitan** [comment]
Thank you for quick reply!
