### ISSUE TITLE
Visual Representation of the model

### ISSUE THREAD

**Issue by GiteshKhanna** [xinyadu/nqg#25]
Hi !
I found the research work that you did really interesting.
I think if there is a visual diagram of how your model is working, it would make it much easier to understand the implementation.

Thanks!

**Comment by xinyadu** [comment]
Hello,

Please see the presentation at my homepage
http://www.cs.cornell.edu/~xdu/papers/acl17_dsc_poster.pdf

**Comment by GiteshKhanna** [comment]
So much better to understand!

Thanks!
