### ISSUE TITLE
What should src_seq_length be to get the exact results from paper?

### ISSUE THREAD

**Issue by TinaB19** [xinyadu/nqg#3]
In the paper, you've mentioned that the number of training data is 70484. But when I run the preprocessing, the number of pairs decreases because some of them have length more than 100. So the results that you reported on the paper are from the whole dataset or when you limit the source length to 100? Thanks

**Comment by xinyadu** [comment]
it's been several months, but yes, I think the length of the input sentence is limited to 100.
