### ISSUE TITLE
could not convert string to float

### ISSUE THREAD

**Issue by hamzaLeb** [xinyadu/nqg#31]
When running the command:
`python preprocess_embedding.py --embedding  <path to embedding txt file> --dict ./data/qg.{src,tgt}.dict --output ./data/qg.{src,tgt}.840B.300d.npy`

I get the error "could not convert string to float" as in preprocess_embedding.py we convert the content of the embedding txt file (.txt) to float (line 50: `word2embedding[line[0]] = np.asarray(map(float, line[1 : ]))`)
 
Am I missing something? The embedded file to give is a .txt file isn't it?

Hope anyone can help me with that. Thank you in advance.

**Comment by hamzaLeb** [comment]
RESOLVED: I just used python3 instead of python. Which means: `python3 preprocess_embedding.py --embedding <path to embedding txt file> --dict ./data/qg.{src,tgt}.dict --output ./data/qg.{src,tgt}.840B.300d.npy`

**Comment by Binathi** [comment]
When running the command
python3 preprocess_embedding.py --embedding ./data_qg/glove.840B.300d.txt --dict ./data/qg.src.dict --output ./data/qg.src.840B.300d.npy
i get the following error:
Unknown word: <blank>
Traceback (most recent call last):
  File "preprocess_embedding.py", line 76, in <module>
    main()
  File "preprocess_embedding.py", line 64, in main
    embedding[i] = word2embedding[w]
TypeError: float() argument must be a string or a number, not 'map'
Can anyone help with this?

**Comment by Binathi** [comment]
> @hamzaLeb 
When running the command
python3 preprocess_embedding.py --embedding ./data_qg/glove.840B.300d.txt --dict ./data/qg.src.dict --output ./data/qg.src.840B.300d.npy
i get the following error:
Unknown word: 
Traceback (most recent call last):
File "preprocess_embedding.py", line 76, in 
main()
File "preprocess_embedding.py", line 64, in main
embedding[i] = word2embedding[w]
TypeError: float() argument must be a string or a number, not 'map'
Can anyone help with this?
