### ISSUE TITLE
Availability of trained models

### ISSUE THREAD

**Issue by rahular** [xinyadu/nqg#9]
Hi, first of all, thank you for open sourcing the code base. In the README you mention that `Paragraph-level model and sentence-level model will be made available soon`.

Can you give a rough timeframe of when these models will be made available?

**Comment by farizrahman4u** [comment]
Trained sentence model (15 epochs)
https://drive.google.com/file/d/16Gi1oZr3mEGMEUCsOQ3whFfDlv8IAyzG/view?usp=sharing

**Comment by rahular** [comment]
@farizrahman4u thanks :)

**Comment by rahular** [comment]
@farizrahman4u  thanks. Is this for sentence or paragraph level?

**Comment by farizrahman4u** [comment]
sentence

**Comment by BurakaKrishna** [comment]
@farizrahman4u Is this a torch model?, i have tried loading in pytorch, and i am facing this error
T7ReaderException: unknown type id 32. The file may be corrupted. 
Can you guide me to how to load it ?

**Comment by hamzaLeb** [comment]
First copy the trained model to sentence/model. 
Then Inside the sentence folder run: `th translate.lua -model model/<model file name> -config config-trans` . You have to change `<model file name>` with the name of the trained model and in config-trans change _src=../data/processed/src-dev.txt_ **to** _src=path_to_your_input_sentence_text_file_
You normally will get the result printed out on the terminal after running the command.
